// Generated by CoffeeScript 1.4.0
(function() {
  var querystring;

  querystring = require('querystring');

  module.exports = function(robot) {
    return robot.router.get("/hubot/say", function(req, res) {
      var fault, query, send;
      query = querystring.parse(req._parsedUrl.query);
      fault = function(msg) {
        res.end("1:" + msg);
      };
      if (!query.message) {
        fault("no message");
      }
      if (!query.room) {
        fault("no room");
      }
      send = function(room, msg) {
        var response;
        response = new robot.Response(robot, {
          user: {
            id: -1,
            name: room
          },
          text: "none",
          done: false
        }, []);
        return response.send(msg);
      };
      send("#" + query.room, query.message);
      return res.end("0");
    });
  };

}).call(this);
